# Copyright (c) 2017 Dell Inc. or its subsidiaries.  All Rights Reserved.
# Dell EMC Confidential/Proprietary Information

version: '2'

services:

  dne-paqx:
    image: cpsd-dne-paqx
    container_name: symphony-dne-paqx
    network_mode: "host"
    command: --spring.cloud.consul.host=${HOSTNAME}
    volumes:
      -  /opt/dell/cpsd/dne-paqx/logs/:/opt/dell/cpsd/dne-paqx/logs
      -  /etc/rabbitmq/:/etc/rabbitmq
    environment:
      -  CREDENTIALS=${CREDENTIALS}
      -  PASSPHRASES=${PASSPHRASES}
      -  remote.dell.amqp.rabbitKeyStorePath=${KEYSTOREPATH}
      -  remote.dell.amqp.rabbitTrustStorePath=${TRUSTSTOREPATH}



# it has dependency on consul container.
# has to connect to same network as consul.
# If consul keeps current network_mode: host, this part is not needed.
# otherwise, need refer to consul network.
#networks:
#  default:
#    external:
#      name: bobuserstory_default
